### PR TITLE
Fix abundancies for monoisotopic abundancies

### LINKED ISSUE #79: wrong abundancies for monoisotopic elements
## Describe the bug
the abundancies for all isotopes of monoisotopic elements are shown as zero, including for the "100%" isotope

## To Reproduce

```
>>> from mendeleev import element
>>> Be = element("Be")
>>> Be.isotopes[4]
<Isotope(Z=4, A=9, mass=9.012183062, abundance=0.0)>

```

## Expected behavior

`<Isotope(Z=4, A=9, mass=9.012183062, abundance=1.0)>`

### PR DESCRIPTION
**Pull request by lmmentel**
Fixes missing abundancies for isotopes with 100% abundance of one isotope

```python
In [2]: from mendeleev import Be

In [3]: Be.isotopes
Out[3]: 
[<Isotope(Z=4, A=5, mass=5.03987, abundance=None)>,
 <Isotope(Z=4, A=6, mass=6.019726409, abundance=None)>,
 <Isotope(Z=4, A=7, mass=7.016928714, abundance=None)>,
 <Isotope(Z=4, A=8, mass=8.005305102, abundance=None)>,
 <Isotope(Z=4, A=9, mass=9.012183062, abundance=100.0)>,
 <Isotope(Z=4, A=10, mass=10.013534692, abundance=None)>,
 <Isotope(Z=4, A=11, mass=11.02166108, abundance=None)>,
 <Isotope(Z=4, A=12, mass=12.026922082, abundance=None)>,
 <Isotope(Z=4, A=13, mass=13.036134506, abundance=None)>,
 <Isotope(Z=4, A=14, mass=14.04289292, abundance=None)>,
 <Isotope(Z=4, A=15, mass=15.053490215, abundance=None)>,
 <Isotope(Z=4, A=16, mass=16.061672036, abundance=None)>]
```

fixes #79

### CODE REVIEW

**Comment by kalvdans** [comment]
abundance can't be None according to https://mendeleev.readthedocs.io/en/stable/data.html#isotopes, needs to be a float. Please return 0.0 for all unstable isotopes.

**Comment by kalvdans** [comment]
What value did you pick for abundance_uncertainty? Sorry, I'm too lazy to dump the database to text..

**Comment by lmmentel** [comment]
> abundance can't be None according to https://mendeleev.readthedocs.io/en/stable/data.html#isotopes, needs to be a float. Please return 0.0 for all unstable isotopes.

Thanks for the input. I actually reverted an earlier decision where missing data was filled with zeros, since I now think that the value of `0.0` is different than - has not been measured. I think that semantically `None` is better than `0.0`. Any thoughts?


> What value did you pick for abundance_uncertainty? Sorry, I'm too lazy to dump the database to 

The uncertainties are floats:

```python
In [3]: from mendeleev import Fe

In [4]: for i in Fe.isotopes:
   ...:     print(i.mass_number, i.abundance, i.abundance_uncertainty)
   ...: 
45 None None
46 None None
47 None None
48 None None
49 None None
50 None None
51 None None
52 None None
53 None None
54 5.845 105.0
55 None None
56 91.754 106.0
57 2.119 29.0
58 0.282 12.0
59 None None
60 None None
61 None None
62 None None
63 None None
64 None None
65 None None
66 None None
67 None None
68 None None
69 None None
70 None None
71 None None
72 None None
73 None None
74 None None
75 None None
```

**Comment by lmmentel** [comment]
After posting uncertainties :point_up:  I realized I didn't multiply by the exponent. Will fix shortly.

**Comment by kalvdans** [comment]
> > abundance can't be None according to https://mendeleev.readthedocs.io/en/stable/data.html#isotopes, needs to be a float. Please return 0.0 for all unstable isotopes.
> 
> Thanks for the input. I actually reverted an earlier decision where missing data was filled with zeros, since I now think that the value of `0.0` is different than - has not been measured. I think that semantically `None` is better than `0.0`. Any thoughts?

If we are sure one isotope is 100% abdundant we are also sure the others are 0%, right? (adding all abdundances must sum to 1)

But if you wish to duplicate the cited source then I'm okay leaving them as None. But then it should be documented that they can be None. Otherwise the whole point of providing an uncertainty is to avoid special casing the unknowns, they could just have uncertainty = 1.0 :)

> The uncertainties are floats:

No, they can also be None as you showed. I would like to see which uncertainties you picked for your newly added certainity data.

**Comment by Eben60** [comment]
An isotopic abundace can be treated as the absolute abundance of an isotope divided by the abundance of the corresponding element. Then, for naturally occurring elements the isotopic abundancies sum to 1.  

For other elements the abundance is 0/0 then.

**Comment by lmmentel** [comment]
> No, they can also be None as you showed. I would like to see which uncertainties you picked for your newly added certainity data.

I was thinking in terms of `SQLAlchemy` classes here since the values where `Float(nullable=True)` so the value is a float if it's present. It's worth bearing in mind that a lot `float` object implmentations include some sort of null value, like 

```python
In [3]: isinstance(math.nan, float)
Out[3]: True
```

**Comment by lmmentel** [comment]
OK, I have now corrected the abundance uncertainties to have correct scale.

```python
In [4]: from mendeleev import Fe
In [5]: for i in Fe.isotopes:
    print(i.mass_number, i.abundance, i.abundance_uncertainty)
45 None None
46 None None
47 None None
48 None None
49 None None
50 None None
51 None None
52 None None
53 None None
54 5.845 0.105
55 None None
56 91.754 0.106
57 2.119 0.029
58 0.282 0.012
59 None None
60 None None
61 None None
62 None None
63 None None
64 None None
65 None None
66 None None
67 None None
68 None None
69 None None
70 None None
71 None None
72 None None
73 None None
74 None None
75 None None
76 None None
```

I have also corrected values where only one stable isotope is present:

```python
In [6]: from mendeleev import Be
In [7]: for i in Be.isotopes:
    print(i.mass_number, i.abundance, i.abundance_uncertainty)
5 None None
6 None None
7 None None
8 None None
9 100.0 0.0
10 None None
11 None None
12 None None
13 None None
14 None None
15 None None
16 None None
```

**Pull request merged**
