### PR TITLE
Change "Oxidation states" to "Commonly occurring oxidation states"

### PR DESCRIPTION
**Pull request by Eben60**
The data do not exhaustively list all possible oxidation states. E.g. for Iron, Wikipedia lists states −4, −2, −1, 0, +1, +2, +3, +4, +5, +6, +7, and Britannica +2, +3, +4, +6. The Mendeleev db list only +2, +3 , which I personally find reasonable - but that should be reflected in the name of the field.

The data may however need some attention. If only oxidation states of an element in chemical compounds are taken into account, then for inert gases no zero oxidation states should listed. Otherwise, for every element a zero oxidation state must be listed. For Xe, only zero oxidation is listed, although stable Xe compounds are known (and used practically). For Os, an oxidation state of -2 is listed, which does exist according to Wikipedia, but is IMO rather unusual for this elements 

I could look over the data, however I'm not a chemist, and a decision which oxistates can be considered as "common" is necessarily a subjective one. Maybe basing decisions on Britannica would be a conservative way.

### CODE REVIEW

**Comment by lmmentel** [comment]
Thanks for looking into this @Eben60. Indeed the oxidation states are not exhaustive since my priority here was usefulness and pragmatism. Some of the exotic oxidation states are not very useful in practices since they are formed under extreme conditions. 

I do not remember exactly where I got the values from, but I found some old scripts from parsing [this wikipedia page](https://en.wikipedia.org/wiki/Oxidation_state) so it's probably it. They are distinguishing the **main oxidation states** so maybe you could the description to that?

On a broader note, maybe you would be interested in adding the remaining oxidation states to the db and coding up some way to fetch either `all` oxidation states or `main` / `most common`. I'm happy to help out with putting in the db/scraping etc. Let me know what you think.

**Comment by Eben60** [comment]
I've now scraped the **main** oxidation states from  [that wikipedia page](https://en.wikipedia.org/wiki/Oxidation_state) and changed a few entries (commenting on all changes). See file [main_oxidation_states.txt](https://github.com/Eben60/Mendeleev.jl/blob/main/auxillary/main_oxidation_states.txt).

**Comment by lmmentel** [comment]
Great, if you can convert the result to sth like a csv it'll be easier to use them.

**Comment by Eben60** [comment]
I've [converted](https://github.com/Eben60/Mendeleev.jl/blob/main/auxillary/main_oxidation_states.py) it to a python dictionary, hope it's ok. I'm nor sure how you are going to implement `missing`s (in Julia it's a built-in type), thus put `missing = [-9223372033146270158]` as a dummy.

**Comment by lmmentel** [comment]
Thanks, looks great. Would you happen to have the data for **all** oxidation states already parsed? Also would you like to try and edit the db to update the values?

**Comment by Eben60** [comment]
> Would you happen to have the data for **all** oxidation states already parsed? 

No, sorry. Actually I parsed the Wikipedia page in a quick, dirty, and irreproducible way by performing multiple regex search-and-replaces in BBEdit editor.

> Also would you like to try and edit the db to update the values?

Probably not, and definitely not in the next future.

**Comment by lmmentel** [comment]
No worries, and thanks for the reply.

I was able to parse all the oxidation states into a dict, posting here in case it might be useful (keys are atomic numbers):

```python
{1: [-1, 1],
 2: [],
 3: [0, 1],
 4: [0, 1, 2],
 5: [-5, -1, 0, 1, 2, 3],
 6: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
 7: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
 8: [-2, -1, 0, 1, 2],
 9: [-1, 0],
 10: [],
 11: [-1, 0, 1],
 12: [0, 1, 2],
 13: [-2, -1, 0, 1, 2, 3],
 14: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
 15: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
 16: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
 17: [-1, 1, 2, 3, 4, 5, 6, 7],
 18: [0],
 19: [-1, 1],
 20: [1, 2],
 21: [0, 1, 2, 3],
 22: [-2, -1, 0, 1, 2, 3, 4],
 23: [-3, -1, 0, 1, 2, 3, 4, 5],
 24: [-4, -2, -1, 0, 1, 2, 3, 4, 5, 6],
 25: [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7],
 26: [-4, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7],
 27: [-3, -1, 0, 1, 2, 3, 4, 5],
 28: [-2, -1, 0, 1, 2, 3, 4],
 29: [-2, 0, 1, 2, 3, 4],
 30: [-2, 0, 1, 2],
 31: [-5, -4, -3, -2, -1, 0, 1, 2, 3],
 32: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
 33: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
 34: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
 35: [-1, 1, 2, 3, 4, 5, 7],
 36: [0, 1, 2],
 37: [-1, 1],
 38: [1, 2],
 39: [0, 1, 2, 3],
 40: [-2, 0, 1, 2, 3, 4],
 41: [-3, -1, 0, 1, 2, 3, 4, 5],
 42: [-4, -2, -1, 0, 1, 2, 3, 4, 5, 6],
 43: [-3, -1, 0, 1, 2, 3, 4, 5, 6, 7],
 44: [-4, -2, 0, 1, 2, 3, 4, 5, 6, 7, 8],
 45: [-3, -1, 0, 1, 2, 3, 4, 5, 6, 7],
 46: [0, 1, 2, 3, 4, 5],
 47: [-2, -1, 0, 1, 2, 3],
 48: [-2, 1, 2],
 49: [-5, -2, -1, 0, 1, 2, 3],
 50: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
 51: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
 52: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
 53: [-1, 1, 2, 3, 4, 5, 6, 7],
 54: [0, 2, 4, 6, 8],
 55: [-1, 1],
 56: [1, 2],
 57: [0, 1, 2, 3],
 58: [2, 3, 4],
 59: [0, 1, 2, 3, 4, 5],
 60: [0, 2, 3, 4],
 61: [2, 3],
 62: [0, 1, 2, 3],
 63: [0, 2, 3],
 64: [0, 1, 2, 3],
 65: [0, 1, 2, 3, 4],
 66: [0, 2, 3, 4],
 67: [0, 2, 3],
 68: [0, 2, 3],
 69: [0, 1, 2, 3],
 70: [0, 1, 2, 3],
 71: [0, 2, 3],
 72: [-2, 0, 1, 2, 3, 4],
 73: [-3, -1, 0, 1, 2, 3, 4, 5],
 74: [-4, -2, -1, 0, 1, 2, 3, 4, 5, 6],
 75: [-3, -1, 0, 1, 2, 3, 4, 5, 6, 7],
 76: [-4, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8],
 77: [-3, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 78: [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6],
 79: [-3, -2, -1, 0, 1, 2, 3, 5],
 80: [-2, 1, 2],
 81: [-5, -2, -1, 1, 2, 3],
 82: [-4, -2, -1, 0, 1, 2, 3, 4],
 83: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
 84: [-2, 2, 4, 5, 6],
 85: [-1, 1, 3, 5, 7],
 86: [2, 6],
 87: [1],
 88: [2],
 89: [2, 3],
 90: [-1, 1, 2, 3, 4],
 91: [2, 3, 4, 5],
 92: [-1, 1, 2, 3, 4, 5, 6],
 93: [2, 3, 4, 5, 6, 7],
 94: [2, 3, 4, 5, 6, 7, 8],
 95: [2, 3, 4, 5, 6, 7],
 96: [3, 4, 5, 6],
 97: [2, 3, 4, 5],
 98: [2, 3, 4, 5],
 99: [2, 3, 4],
 100: [2, 3],
 101: [2, 3],
 102: [2, 3],
 103: [3],
 104: [4],
 105: [5],
 106: [0, 6],
 107: [7],
 108: [8],
 109: [],
 110: [],
 111: [],
 112: [2],
 113: [],
 114: [],
 115: [],
 116: [],
 117: [],
 118: []}
```

I have a bit of time so I'll try to refactor the update the oxidation states. Let me know if you spot anything else worth looking into.

**Review by lmmentel — APPROVED** [review]

**Comment by Eben60** [comment]
Please note that the empty arrays have different meanings for He and Ne (inert) and for elements 109 ff. (no data)

**Pull request merged**
