### PR TITLE
added isotopes list from http://nucleardata.nuclear.lu.se/

### PR DESCRIPTION
**Pull request by guilindner**
Added additional Isotopes data from The Lund/LBNL Nuclear Data [http://nucleardata.nuclear.lu.se/](url), and the National Institute of Standards and Technology (NIST) [https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl?ele=&isotype=all](url).

### CODE REVIEW

**Comment by lmmentel** [comment]
Great work! I would love to see atrue diff of the data you added to get a better feel of the changes. That's kinda tricky with the db being a binary file but I found a CLI tool called `sqldiff` and made a quick sanity check. Here are some observations, before your update there were 406 rows in the `isotopes` table, after 3714 and the diff I got from comparing the dbs  has exactly 3714 records which mean all the data are modified in that table. I checked a bit closer and 406 records are of type `UPDATE` (edits of the existing data) and the rest are `INSERT` which makes sense :slightly_smiling_face: If you don't mind I would like to ask was what was the reason you decided to update the existing isotope data and which properties were updated?

Moving forward it would also be great if you could update the docs [data.rst](https://github.com/lmmentel/mendeleev/blob/master/docs/source/data.rst) with the references to the new data source.

I you feel like it might be useful for others you could also include your code for fetching data (I already included some in the notebooks folder) but I leave it up to if you want to do that.

**Comment by guilindner** [comment]
Hi,
This `sqldiff` tool is very nice, I didn't know about it. I checked and is is indeed an UPDATE on the existing 406 records, but what I did is delete all the isotopes entries and recreate all of them from the same source.
The date 1999 database is old indeed, but the revised properties (mass, mass uncertaintly, ...) are found in the other newer sources (NIST and easypin for example) 
I noticed that I'm missing the`quadrupole_moment` and `g_factor`, so I will just use the same source as you [https://easyspin.org/easyspin/documentation/isotopetable.html](url).
The code used to fetch data from the website is avaiable currently at my fork, but I need to refactor it (it was suppose to be a single use code).
Let me play a little bit with these databases and find a clean and simple way to maintain it.

**Comment by lmmentel** [comment]
The update looks really good! I am wondering however if there is a way to keep the original CIAAW isotope data (since it is the de facto standard) and only updating the data on the remaining isotopes from the Lund database. This would have the advantage of using the latest data whenever possible and complementing it with the other source. That will however require putting some extra comments into the docs explaining the situation.  Let me know what you think.

BTW I glanced at your code and I saw that you are using SQL directly to insert data, which is one way of updating the db, another way that I have used is to use SQLAlchemy ORM to create/update records. You can see an example [in this notebook](https://github.com/lmmentel/mendeleev/blob/master/notebooks/polarizability2018.ipynb) if you are interested.

**Comment by guilindner** [comment]
I agree that the best is to keep the original CIAAW isotope data, I will keep it simple and build on top of your data.
The SQLAlchemy is great, I had to learn how to use it and now I see the advantage. The new update method is working and I will refactor the code following your coding style.
Do you think the best is to close this pull request and I submit a totally new one or if I revert my master branch back it will update here once I push it?

**Comment by lmmentel** [comment]
I'm glad you liked SQLAlchemy, it pretty neat once you get the hang of it. As for the PR I think it's best if you would keep pushing commits to this PR since then will have the discussion and code in one place.

**Comment by guilindner** [comment]
A few questions regarding the isotopes:
- Is it possible for the **mass_uncertainty** be defined as integer in the database? I think it fits better the definition.
- How can we handle an isomer? For example 53Fe and 53mFe (http://nucleardata.nuclear.lu.se/toi/listnuc.asp?Z=26), they share the same atomic and mass numbers but they are quite different.
 
I'm doing some test on a different branch now, the additional isotopes are populated with a simplified code based on your notebooks and SQLAlchemy. https://github.com/guilindner/mendeleev/commit/3480738584560e57a33b2a6a7c55ea51298f1df4

**Comment by lmmentel** [comment]
> Is it possible for the mass_uncertainty be defined as integer in the database? I think it fits better the definition.

Yes it is absolutely possible but I see limited value of switching since currently uncertainty has the same unit as mass and therefore  the values can be use together without conversions. If I understand correctly this would require storing two integers: the decimal and the exponent (without getting into some weird conventions.), which would raise the effort for anyone truing to use those values. I am trying to stick to a pattern where data should be stored as it will be used once retrieved and   didn't find a case of using uncertainty as integers. Have you found a case when it more convenient to have integers?

> How can we handle an isomer? For example 53Fe and 53mFe (http://nucleardata.nuclear.lu.se/toi/listnuc.asp?Z=26), they share the same atomic and mass numbers but they are quite different.

As far as I can see there should be no difficulties in storing those values since these would be just additional rows in the isotopes table. The might be some issues with accessing isotopes by atomic and mass number but that can be tested against.

**Pull request closed without merging**
