### PR TITLE
Fix the vdw_radius_rt values to correspond to the reference

### LINKED ISSUE #44: Rowland-Taylor VdW radii assigned to wrong element
## Describe the bug
Rowland-Taylor VdW radii assigned to wrong element after fluorine.

## To Reproduce
```py
from mendeleev import element

for i in range(1, 119):
    e = element(i)
    r = e.vdw_radius_rt
    if r is not None:
        print(e.symbol, int(r))
```

## Observed behavior
```
H 110
C 177
N 164
O 158
F 146
Ne 181
Na 176
Mg 187
Al 202
```

## Expected behavior
```
H 110
C 177
N 164
O 158
F 146
S 181
Cl 176
Br 187
I 202
```

## Specification

- mendleev 0.9.0
- python 3.8.12
- WSL on Windows 11

## Additional context
Original publication: _J. Phys. Chem._ **1996**, _100_, 7384.

### PR DESCRIPTION
**Pull request by lmmentel**
fixes #44

### CODE REVIEW

**Comment by kalvdans** [comment]
Could you add a unit test that fails before the change, and succeeds after the change?

**Comment by lmmentel** [comment]
I don't think that it would be helpful since the change is correcting the data in the db and not the code  the test would end up being a bit redundant.

**Comment by kalvdans** [comment]
Pro tip for reviewers: To view the change in text, run these commands:
```
echo "*.db diff=sqlite3" > .gitattributes
echo '[diff "sqlite3"]' >> ~/.gitconfig
echo '        textconv = echo .dump | sqlite3 -batch' >>  ~/.gitconfig
git diff HEAD HEAD^ --word-diff
```

It shows unrelated changes, for example `[Ne] [-3s2` to `[Ne] {+3s2` but not sure if it is the sorting order that results in that change.

**Comment by lmmentel** [comment]
Thanks for checking. I'm not quite sure that the commands you used are doing but I usually use `sqldiff` to view changes between databases. If I compare `elements.db` between master vs this branch, I get

```
UPDATE elements SET vdw_radius_rt=NULL WHERE atomic_number=10;
UPDATE elements SET vdw_radius_rt=NULL WHERE atomic_number=11;
UPDATE elements SET vdw_radius_rt=NULL WHERE atomic_number=12;
UPDATE elements SET vdw_radius_rt=NULL WHERE atomic_number=13;
UPDATE elements SET vdw_radius_rt=181.0 WHERE atomic_number=16;
UPDATE elements SET vdw_radius_rt=176.0 WHERE atomic_number=17;
UPDATE elements SET vdw_radius_rt=187.0 WHERE atomic_number=35;
UPDATE elements SET vdw_radius_rt=203.0 WHERE atomic_number=53;
```
which is exactly what I intended.

**Comment by kalvdans** [comment]
Thanks. I can confirm that sqldiff shows that output. sqldiff is a bit tricky to integrate with git. The earlier changes I saw was the diff markup characters inserted by `--word-diff` tool.

I agree unit tests are kind of useless.

LGTM!

**Pull request merged**
